services:
  apco_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4040:4000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
    depends_on:
      - redis
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    networks:
      - shared-network

  redis:
    image: redis:7.2
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared-network

volumes:
  bundle_cache:
  redis_data:

networks:
  shared-network:
    external: true

